version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: cineach
      POSTGRES_USER: adry
      POSTGRES_PASSWORD: password_adry_default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/cinema_backend
    container_name: django_backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/cinema_backend:/app

    environment:
      - DB_HOST=db
      - DB_NAME=cineach
      - DB_USER=adry
      - DB_PASS=password_adry_default
    depends_on:
      - db
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: ./frontend/dashboard
    container_name: dashboard_frontend
    volumes:
      - ./frontend/dashboard:/frontend/app
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"

  totem:
    build:
      context: ./frontend/totem
    container_name: totem_frontend
    volumes:
      - ./frontend/totem:/frontend/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:
