from .admin_client_view import *
from .admin_login_view import *
from .cinema_employee_view import *
from .cinema_report_view import *
from .cinema_view import *
from .client_login_view import *
from .client_order_view import *
from .client_points_view import *
from .client_profile_view import *
from .client_register_view import *
from .employee_view import *
from .movie_view import *
from .report_view import *
from .room_view import *
from .session_view import *
from .totem_cinema_view import *
from .totem_movie_view import *
from .totem_payment_view import *
from .totem_seat_view import *
from .totem_session_view import *
from .totem_ticket_view import *

from .example_view import *
