# Generated by Django 5.1.3 on 2024-11-12 14:02

from django.db import migrations, connection
import os

def load_sql_file(apps, schema_editor):
    sql_file_path = os.path.join(os.path.dirname(__file__), '..', '..', 'schemas', 'cinema-DML.sql')
    sql_file_path = os.path.abspath(sql_file_path)
    with open(sql_file_path, 'r') as f:
        sql_commands = f.read()

    with connection.cursor() as cursor:
        statements = [cmd.strip() for cmd in sql_commands.split(';') if cmd.strip()]
        for statement in statements:
            cursor.execute(statement)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_DDL'),
    ]

    operations = [
        migrations.RunPython(load_sql_file),
    ]

