# Generated by Django 5.1.3 on 2025-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(blank=True, choices=[(0, 'employee'), (1, 'staff'), (2, 'admin')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
